#!/usr/bin/env python3
"""Build quill's bundled Source Serif 4 faces from the upstream variable fonts.

The four faces in `crates/fonts/assets/` are *static instances* of Google Fonts'
Source Serif 4 variable fonts, pinned to one optical size and one weight, then
subset to the character set quill ships. They carry no `fvar`, which is why a
bold or an italic cannot be instanced from the regular at run time and has to be
its own program in the repository.

Provenance (recorded so the artifacts can be rebuilt or audited):

    upstream   https://github.com/google/fonts/tree/main/ofl/sourceserif4
               SourceSerif4[opsz,wght].ttf         (roman)
               SourceSerif4-Italic[opsz,wght].ttf  (italic)
    version    4.004 (Version 4.004;hotconv 1.0.116;makeotfexe 2.5.65601)
    licence    SIL Open Font License 1.1 — that directory's OFL.txt is committed
               verbatim as `SourceSerif4-LICENSE.txt` (byte-identical)
    instance   opsz=14, wght=400 (regular, italic) / wght=700 (bold, bold italic)
    overlaps   removed (skia-pathops), as the pre-existing regular's are
    subset     the 231 codepoints the pre-existing regular covers, so no face
               resolves a character another face would refuse

`SourceSerif4-Regular.ttf` predates this script and is **not** regenerated by it:
its glyph outlines are the anchor every export byte-hash in the workspace has
been measured against since spec 0001, and a newer fontTools rounds a handful of
its points by one unit per em. `--check` verifies the recipe still reproduces it
to within that one-unit rounding, which is what makes the provenance above a
claim rather than a comment.

Usage (needs `fonttools` and `skia-pathops`, neither a workspace dependency):

    python3 tools/fonts/build-faces.py --download   # fetch upstream to a temp dir
    python3 tools/fonts/build-faces.py --check      # verify the regular's recipe
"""

from __future__ import annotations

import argparse
import sys
import tempfile
import urllib.request
from pathlib import Path

from fontTools import subset
from fontTools.pens.boundsPen import ControlBoundsPen
from fontTools.pens.recordingPen import RecordingPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

REPO = Path(__file__).resolve().parents[2]
ASSETS = REPO / "crates" / "fonts" / "assets"
REGULAR = ASSETS / "SourceSerif4-Regular.ttf"

UPSTREAM = "https://github.com/google/fonts/raw/main/ofl/sourceserif4/"
ROMAN_URL = UPSTREAM + "SourceSerif4%5Bopsz%2Cwght%5D.ttf"
ITALIC_URL = UPSTREAM + "SourceSerif4-Italic%5Bopsz%2Cwght%5D.ttf"
LICENSE_URL = UPSTREAM + "OFL.txt"

OPSZ = 14

# (output stem, source, weight, italic, subfamily, macStyle, fsSelection)
FACES = [
    ("SourceSerif4-Regular", "roman", 400, False, "Regular", 0x0000, 0x0040),
    ("SourceSerif4-Bold", "roman", 700, False, "Bold", 0x0001, 0x0020),
    ("SourceSerif4-Italic", "italic", 400, True, "Italic", 0x0002, 0x0001),
    ("SourceSerif4-BoldItalic", "italic", 700, True, "Bold Italic", 0x0003, 0x0021),
]


def charset() -> list[int]:
    """The codepoints the bundled regular covers — every face gets exactly these."""
    return sorted(TTFont(REGULAR).getBestCmap())


def build(source: Path, weight: int, subfamily: str, stem: str, macstyle: int, fssel: int) -> TTFont:
    font = TTFont(source)
    instancer.instantiateVariableFont(
        font,
        {"wght": weight, "opsz": OPSZ},
        inplace=True,
        overlap=instancer.OverlapMode.REMOVE,
    )

    # Subsetter defaults, plus the two the pre-existing regular was clearly built
    # with: no `BASE`/`DSIG`, no hinting programs. Everything else is left at the
    # default so the new faces carry the same layout features and the same name
    # records the regular does — a bold that shaped through a different feature
    # set than the regular would break the paragraph at the face boundary.
    options = subset.Options()
    options.drop_tables += ["BASE", "DSIG"]
    options.hinting = False
    options.notdef_outline = True  # the regular's `.notdef` is drawn, not blank
    # Keep the copyright and both licence records: the OFL asks that they travel
    # with the program, and a subset that drops them ships a font whose own
    # metadata no longer says what it is licensed under.
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=charset())
    subsetter.subset(font)

    # Face identity. The upstream names carry the variable font's "Roman"/"Italic"
    # source family (`SourceSerif4Roman-Regular`); the shipped faces are named for
    # the style they are, which is what `export-pdf` writes as the PostScript name.
    full = f"Source Serif 4 {subfamily}"
    version = font["name"].getDebugName(5) or "Version 4.004"
    for record in list(font["name"].names):
        if record.nameID in (1, 16):
            font["name"].setName("Source Serif 4", record.nameID, record.platformID,
                                 record.platEncID, record.langID)
        elif record.nameID in (2, 17):
            font["name"].setName(subfamily, record.nameID, record.platformID,
                                 record.platEncID, record.langID)
        elif record.nameID == 3:
            font["name"].setName(f"4.004;ADBO;{stem}", record.nameID, record.platformID,
                                 record.platEncID, record.langID)
        elif record.nameID == 4:
            font["name"].setName(full, record.nameID, record.platformID,
                                 record.platEncID, record.langID)
        elif record.nameID == 6:
            font["name"].setName(stem, record.nameID, record.platformID,
                                 record.platEncID, record.langID)
        elif record.nameID == 25:
            font["name"].removeNames(25)
    assert version  # the version string is upstream's and is left alone

    font["OS/2"].usWeightClass = weight
    font["OS/2"].fsSelection = fssel
    font["head"].macStyle = macstyle
    return font


def bounds(font: TTFont) -> dict[int, tuple]:
    glyphs = font.getGlyphSet()
    out = {}
    for cp, name in font.getBestCmap().items():
        pen = ControlBoundsPen(glyphs)
        glyphs[name].draw(pen)
        out[cp] = pen.bounds
    return out


def structure(font: TTFont) -> dict[int, list]:
    glyphs = font.getGlyphSet()
    out = {}
    for cp, name in font.getBestCmap().items():
        pen = RecordingPen()
        glyphs[name].draw(pen)
        out[cp] = [op for op, _ in pen.value]
    return out


def check(roman: Path) -> int:
    """Verify the recipe still reproduces the committed regular.

    Not byte-for-byte, and deliberately not: overlap removal is a boolean
    operation whose *point count* moves between skia-pathops releases even when
    the resulting shape does not. What must not move is what typesetting reads —
    the coverage, the advance widths, and the glyph bounds. Point-structure
    differences are reported, not failed on.
    """
    want = TTFont(REGULAR)
    got = build(roman, 400, "Regular", "SourceSerif4-Regular", 0x0000, 0x0040)

    wc, gc = want.getBestCmap(), got.getBestCmap()
    if set(wc) != set(gc):
        print(f"FAIL: coverage differs by {len(set(wc) ^ set(gc))} codepoints")
        return 1

    wh, gh = want["hmtx"], got["hmtx"]
    advances = [cp for cp in wc if wh[wc[cp]][0] != gh[gc[cp]][0]]

    wb, gb = bounds(want), bounds(got)
    worst = 0.0
    for cp in wc:
        a, b = wb[cp], gb[cp]
        if a is None or b is None:
            if a != b:
                advances.append(cp)
            continue
        worst = max(worst, max(abs(p - q) for p, q in zip(a, b)))

    ws, gs = structure(want), structure(got)
    repointed = sum(1 for cp in wc if ws[cp] != gs[cp])

    print(f"coverage:  {len(wc)} codepoints, identical")
    print(f"advances:  {len(advances)} differ")
    print(f"bounds:    worst {worst} units/em")
    print(f"structure: {repointed} glyphs re-pointed by overlap removal (informational)")
    if advances or worst > 1:
        print("FAIL: the recipe no longer reproduces the committed regular")
        return 1
    print("OK: recipe reproduces the committed regular within 1 unit/em")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--roman", type=Path, help="SourceSerif4[opsz,wght].ttf")
    ap.add_argument("--italic", type=Path, help="SourceSerif4-Italic[opsz,wght].ttf")
    ap.add_argument("--download", action="store_true", help="fetch upstream first")
    ap.add_argument("--check", action="store_true",
                    help="verify the recipe reproduces the committed regular, write nothing")
    args = ap.parse_args()

    tmp = Path(tempfile.mkdtemp(prefix="ss4-"))
    if args.download:
        args.roman = tmp / "roman.ttf"
        args.italic = tmp / "italic.ttf"
        for url, dest in ((ROMAN_URL, args.roman), (ITALIC_URL, args.italic)):
            print(f"fetching {url}")
            urllib.request.urlretrieve(url, dest)
        print(f"fetching {LICENSE_URL}")
        licence = tmp / "OFL.txt"
        urllib.request.urlretrieve(LICENSE_URL, licence)
        committed = ASSETS / "SourceSerif4-LICENSE.txt"
        if licence.read_bytes() != committed.read_bytes():
            print(f"WARNING: upstream OFL.txt differs from {committed.relative_to(REPO)}")
        else:
            print(f"licence: {committed.relative_to(REPO)} matches upstream byte-for-byte")
    if not args.roman or not args.italic:
        ap.error("need --roman and --italic, or --download")

    if args.check:
        return check(args.roman)

    for stem, source, weight, _italic, subfamily, macstyle, fssel in FACES:
        if stem == "SourceSerif4-Regular":
            continue  # pre-existing artifact; see the module docstring
        src = args.roman if source == "roman" else args.italic
        font = build(src, weight, subfamily, stem, macstyle, fssel)
        out = ASSETS / f"{stem}.ttf"
        font.save(out)
        print(f"wrote {out.relative_to(REPO)} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
